name: Run Renovate

on:
  workflow_dispatch:
    inputs:
      log_level:
        description: 'Log level for Renovate'
        required: false
        default: 'info'
        type: choice
        options:
          - debug
          - info
          - warn
          - error
  schedule:
    - cron: '0 12 * * *'

jobs:
  run-renovate:
    name: Renovate
    runs-on: native
    steps:
      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: Renovate
        run: nix run .#renovate-wrapped
        env:
          RENOVATE_TOKEN: ${{ secrets.RENOVATE_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.RENOVATE_GITHUB_TOKEN }}
          LOG_LEVEL: ${{ inputs.log_level || 'info' }}
